<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Points Message for cart and checkout" => array(
		__( "Points Message for cart and checkout", 'yith-woocommerce-points-and-rewards' ),
	),
	"Show points message in cart and checkout." => array(
		__( "Show points message in cart and checkout.", 'yith-woocommerce-points-and-rewards' ),
	),
	"Rewards Points Message for cart and checkout" => array(
		__( "Rewards Points Message for cart and checkout", 'yith-woocommerce-points-and-rewards' ),
	),
	"Show rewards points message in cart and checkout." => array(
		__( "Show rewards points message in cart and checkout.", 'yith-woocommerce-points-and-rewards' ),
	),
	"Form Step Options" => array(
		__( "Form Step Options", 'yith-woocommerce-points-and-rewards' ),
	),
	"Show step number" => array(
		__( "Show step number", 'yith-woocommerce-points-and-rewards' ),
	),
	"Date of Birth" => array(
		__( "Date of Birth", 'yith-woocommerce-points-and-rewards' ),
	),
	"Day" => array(
		__( "Day", 'yith-woocommerce-points-and-rewards' ),
	),
	"Month" => array(
		__( "Month", 'yith-woocommerce-points-and-rewards' ),
	),
	"Year" => array(
		__( "Year", 'yith-woocommerce-points-and-rewards' ),
	),
	"Please set a valid date" => array(
		__( "Please set a valid date", 'yith-woocommerce-points-and-rewards' ),
	),
	"block titleDate of Birth" => array(
		_x( "Date of Birth", "block title", 'yith-woocommerce-points-and-rewards' ),
	),
	"block descriptionAdd a Date of Birth field in checkout" => array(
		_x( "Add a Date of Birth field in checkout", "block description", 'yith-woocommerce-points-and-rewards' ),
	),
);