<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'KrokedilAvardaDeps\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'KrokedilAvardaDeps\\Krokedil\\WooCommerce\\' => array($vendorDir . '/krokedil/woocommerce/src'),
    'KrokedilAvardaDeps\\Krokedil\\Shipping\\' => array($vendorDir . '/krokedil/shipping/src'),
    'KrokedilAvardaDeps\\Krokedil\\SettingsPage\\' => array($vendorDir . '/krokedil/settings-page/src'),
);
